### PR TITLE
Enable selecting wallpapers from subdirectories, don't require xsettingsd for gtk3 live reload

### PR DESCRIPTION
**Pull request by jasperro**
Combined https://github.com/deviantfero/wpgtk/pull/187, https://github.com/deviantfero/wpgtk/pull/186 to resolve merge conflicts.

### CODE REVIEW

**Comment by jasperro** [comment]
@deviantfero, I also made a updated version of FlatColor at https://github.com/jasperro/FlatColor.

**Comment by deviantfero** [comment]
could you give me write access to your fork? I want to test this code and do some changes, what do you mean "select wallpapers from subdirectories"?

**Comment by jasperro** [comment]
@deviantfero Just gave access to you, this patch allows for subdirectories in ~/.config/wpg/wallpapers, like for instance ~/.config/wpg/wallpapers/Abstract or ~/.config/wpg/wallpapers/Nature

**Comment by deviantfero** [comment]
I'm gonna be checking this out soon, but I'm swamped with work so I haven't had a chance yet

**Comment by Misterio77** [comment]
I think gsettings requires some gnome packages.
Xsettingsd is used instead for this reason.
See #112

**Comment by jasperro** [comment]
@deviantfero This patch requires gnome-settings-daemon instead of xsettingsd, but xsettingsd stopped working for me, at least fully on swaywm, and partially on i3. Maybe it's best to allow the choice between gnome-settings-daemon and xsettingsd? gnome-settings-daemon doesn't have many dependencies other than gnome-desktop(3.1MB), gtk3 and systemd-libs(1.8MB), but that just might be too much for this tool.

**Comment by deviantfero** [comment]
I've removed changes regarding subdirectories on `WALL_DIR`, users are not suposed to edit that directory manually, the changes were making theme's sample image logic throw exceptions left and right.

I've edited your gsettings changes a little bit in order to support both xsettingsd and gsettings, but only if those binaries are indeed installed in the system, wpgtk will still prefer xsettingsd though

**Comment by jasperro** [comment]
@deviantfero gsettings changes work for me. I'll keep using my `jasperro` branch with subdirectories (to keep wallpapers organised), but I totally understand you don't want to ship a half-baked/unintended patch. Maybe it is possible to do something else like being able to import specific directories into wpg instead of seperate files, symlinked into .config/wpg/wallpapers or something else to not need to use the .config/wpg directory for this.

Also, what kind of exceptions do you mean with the sample images, I don't seem to be having any issues with this?

**Comment by deviantfero** [comment]
do you use the GUI on wpgtk? any time sample images are involved things go awry because it apparently doesn't handle your use case, let me know if that's not the case

**Pull request merged**
